name: Tests
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'
      - 'vitest.config.ts'
      - '.github/workflows/tests.yaml'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'vitest.config.ts'
      - '.github/workflows/tests.yaml'
  workflow_dispatch:
env:
  CI: true
jobs:
  test:
    if: github.repository == 'vnphanquang/remark-enhance-codeblock'
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            cache-path: ~/.cache/ms-playwright
          - os: macos-latest
            cache-path: ~/Library/Caches/ms-playwright
          - os: windows-latest
            cache-path: '~\AppData\Local\ms-playwright'

    runs-on: ${{ matrix.os }}
    environment: ${{ matrix.environment }}
    continue-on-error: ${{ matrix.continue-on-error || false }}
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint
        run: pnpm lint

      - name: Get Playwright Version
        id: playwright-version
        shell: bash
        run: echo "version=$(pnpm exec playwright --version | cut -d' ' -f2)" >> $GITHUB_OUTPUT

      - name: Cache Playwright Browsers
        uses: actions/cache@v6
        id: playwright-cache
        with:
          path: ${{ matrix.cache-path }}
          key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright Browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm dlx playwright install --with-deps

      - name: Run Tests
        run: 'pnpm ci:test'

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          files: ./coverage/lcov.info
          flags: ${{ runner.os }}
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
